name: Deploy Management Subscription

on:
  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        description: Terraform Apply

jobs:
  tf_fmt:
    name: Deploy Management
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Concat Vars
      run: cat env/terraform.global.tfvars env/terraform.management.tfvars > temp.tfvars && cat temp.tfvars > terraform.management.tfvars

    - name: Terraform init
      id: init
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_TENANT_ID:  ${{ secrets.TENANT_ID }}
        ARM_SUBSCRIPTION_ID:  ${{ secrets.MGMT_SUB_ID }}
    
    - name: Terraform validate
      id: validate
      run: terraform validate
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_TENANT_ID:  ${{ secrets.TENANT_ID }}
        ARM_SUBSCRIPTION_ID:  ${{ secrets.MGMT_SUB_ID }}
    
    - name: Terraform workspace
      id: workspace
      run: terraform workspace select management
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_TENANT_ID:  ${{ secrets.TENANT_ID }}
        ARM_SUBSCRIPTION_ID:  ${{ secrets.MGMT_SUB_ID }}
 
    - name: Terraform plan
      id: plan
      run: terraform plan -var-file="terraform.management.tfvars"
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_TENANT_ID:  ${{ secrets.TENANT_ID }}
        ARM_SUBSCRIPTION_ID:  ${{ secrets.MGMT_SUB_ID }}
 
    - name: Terraform apply
      if: ${{ inputs.deploy }}
      id: apply
      run: terraform apply -auto-approve -var-file="terraform.management.tfvars"
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_TENANT_ID:  ${{ secrets.TENANT_ID }}
        ARM_SUBSCRIPTION_ID:  ${{ secrets.MGMT_SUB_ID }}
