name: 'Sync from remote'

on:
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  
jobs:
  remote-repo-sync:
    uses: Insight-Services-APAC/reusable-workflows/.github/workflows/get-changes-from-disconnected-repo.yml@main
    with:
      remote-repo-url: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale